services:
  ultimate-database:
    container_name: ultimate-database
    image: postgres:15.13-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_DB:-db}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_DB:-db}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - ultimate-verdict
    restart: unless-stopped

  ultimate-backend:
    container_name: ultimate-backend
    image: ultimate-backend:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - ultimate-verdict
    depends_on:
      ultimate-database:
        condition: service_healthy

  ultimate-frontend:
    container_name: ultimate-frontend
    image: ultimate-frontend:1.0
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - 8081:80
    networks:
      - ultimate-verdict
    depends_on:
      - ultimate-backend

networks:
  ultimate-verdict:
    name: ultimate-verdict
