services:
  ultimate-database:
    container_name: ultimate-database
    image: postgres:15.13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_DB:-db}
    volumes:
      - ultimate-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_DB:-db}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s
    networks:
      - ultimate-verdict

  ultimate-backend:
    container_name: ultimate-backend
    image: ultimate-backend:1.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_DB: ${DB_DB:-db}
      DB_HOST: ${DB_HOST:-ultimate-database}
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - ultimate-verdict
    depends_on:
      ultimate-database:
        condition: service_healthy

  ultimate-frontend:
    container_name: ultimate-frontend
    image: ultimate-frontend:1.0
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8080}
    ports:
      - 8081:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - ultimate-verdict
    depends_on:
      - ultimate-backend

volumes:
  ultimate-data:
    name: ultimate-data

networks:
  ultimate-verdict:
    name: ultimate-verdict
